#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Provisions what the Concierge needs outside the repo (#34): Cloudflare AI
# Gateway with Unified Billing (Cloudflare credits pay the model provider, so
# there's no provider key), logging, authentication and a spend limit, plus the
# Worker secrets in .dev.vars (for `wrangler dev`) and on the deployed Worker.
# Run from anywhere: ./scripts/setup-concierge.sh

cd "$(dirname "$0")/.."
ENV_FILE=".dev.vars"

TOTAL_STAGES=6
TOTAL_MINUTES=12

# The `default` gateway is created automatically on the first authenticated
# request; the dashboard has no "Create gateway" button any more.
GATEWAY="default"
# Chosen on 2026-09-28 by benchmarking through the gateway (see #34): fastest
# model that kept the [[id]] format. OpenAI models need max_completion_tokens.
MODEL="openai/gpt-6-luna"
REASONING_EFFORT="none"

banner "Concierge: AI Gateway setup"

# ── 1. Account ID ─────────────────────────────────────────────────────────
stage "Cloudflare account ID" 1
say "The gateway URL is scoped to your Cloudflare account."
say "It's the same value as the CLOUDFLARE_ACCOUNT_ID repo secret used by CI."
if npx --no-install wrangler whoami >/dev/null 2>&1; then
  note "wrangler is logged in. Your accounts:"
  npx --no-install wrangler whoami 2>/dev/null | grep -iE "account|│" || true
else
  open_url "https://dash.cloudflare.com/"
  step "Open the account → Account home → the ⋯ menu next to the account name → Copy account ID."
fi
ask CF_ACCOUNT_ID "Paste the account ID:"
write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"
write_env CF_AI_GATEWAY "$GATEWAY"
pause

# ── 2. Gateway token ──────────────────────────────────────────────────────
stage "Create the gateway token" 2
open_url "https://dash.cloudflare.com/${CF_ACCOUNT_ID}/ai/ai-gateway"
step "Click 'Create authentication token'. Name it jorgemasta-com-concierge."
step "Permissions: keep only Account → AI Gateway → Run. Remove the Workers AI rows (✕)."
step "Account Resources: include only this account. Create, then copy the token (shown once)."
warn "The token is account-scoped: it can run any gateway in this account."
ask_secret CF_AIG_TOKEN "Paste the gateway token (hidden):"
write_env CF_AIG_TOKEN "$CF_AIG_TOKEN"
pause

# ── 3. Credits ────────────────────────────────────────────────────────────
stage "Load Unified Billing credits" 2
say "Cloudflare pays the model provider and deducts from these credits,"
say "so no OpenAI/xAI key is needed. Credit purchases carry a 5% fee."
step "On the AI Gateway page, add credits (e.g. \$10)."
step "Leave auto top-up OFF, so the credits are a hard ceiling on spend."
pause "Press Enter once credits are loaded"

# ── 4. Smoke test ─────────────────────────────────────────────────────────
stage "Test ${MODEL} through the gateway" 2
url="https://gateway.ai.cloudflare.com/v1/${CF_ACCOUNT_ID}/${GATEWAY}/compat/chat/completions"
say "POST $url"
note "The first authenticated request creates the '${GATEWAY}' gateway."
body=$(mktemp)
code=$(curl -sS -o "$body" -w '%{http_code}' "$url" \
  -H 'content-type: application/json' \
  -H "cf-aig-authorization: Bearer ${CF_AIG_TOKEN}" \
  --data "{\"model\":\"${MODEL}\",\"reasoning_effort\":\"${REASONING_EFFORT}\",\"max_completion_tokens\":20,\"messages\":[{\"role\":\"user\",\"content\":\"Reply with exactly: gateway ok\"}]}" \
  || echo "000")
if [[ "$code" == "200" ]]; then
  printf '  %s✓ HTTP 200%s  reply: %s\n' "$GREEN" "$RESET" \
    "$(grep -o '"content": *"[^"]*"' "$body" | head -n1 | sed 's/.*: *"//; s/"$//')"
else
  warn "HTTP $code. Response:"
  note "$(head -c 600 "$body")"
  note "401 → token. 'No credentials presented' → no credits, or the model isn't on Unified Billing."
  SKIPPED+=("Smoke test failed (HTTP $code): fix, then re-run this wizard (Enter keeps saved values)")
fi
rm -f "$body"
pause

# ── 5. Gateway settings ───────────────────────────────────────────────────
stage "Lock down the '${GATEWAY}' gateway" 3
open_url "https://dash.cloudflare.com/${CF_ACCOUNT_ID}/ai/ai-gateway"
step "Open '${GATEWAY}' → Logs: the test request should be there, with a cost."
step "Settings → make sure log collection is ON (questions feed future evals)."
step "Settings → Authenticated Gateway → toggle ON."
step "Settings → Spend limits → add rule: \$1, window 1 day, Sliding, no provider/model/metadata."
note "~\$0.0003 per question on ${MODEL}; \$1/day also stops an abuse spike draining all credits."
if ! confirm "Logs show a cost, authentication is on and the spend limit is saved?"; then
  SKIPPED+=("Gateway settings: logs, Authenticated Gateway and spend limit on '${GATEWAY}'")
fi

# ── 6. Deployed Worker secrets ────────────────────────────────────────────
stage "Push secrets to the deployed Worker" 2
say "Sets CF_ACCOUNT_ID, CF_AI_GATEWAY and CF_AIG_TOKEN as secrets on the"
say "production Worker (jorgemasta-com). Only needed once the Concierge ships."
if confirm "Push the 3 secrets to the deployed Worker now?"; then
  if ! npx --no-install wrangler whoami >/dev/null 2>&1; then
    warn "wrangler isn't logged in. Run: npx wrangler login, then re-run this wizard."
    SKIPPED+=("Deployed Worker secrets (wrangler not logged in)")
  else
    for name in CF_ACCOUNT_ID CF_AI_GATEWAY CF_AIG_TOKEN; do
      if printf '%s' "${!name}" | npx --no-install wrangler secret put "$name" >/dev/null 2>&1; then
        printf '  %s✓ set%s Worker secret %s\n' "$GREEN" "$RESET" "$name"
      else
        warn "couldn't set Worker secret $name"
        SKIPPED+=("Worker secret $name (npx wrangler secret put $name)")
      fi
    done
  fi
else
  SKIPPED+=("Deployed Worker secrets: run  npx wrangler secret bulk .dev.vars  when the Concierge ships")
fi
pause

finish
say "Next: ${BOLD}npx wrangler dev${RESET} reads ${ENV_FILE}. Names are documented in .dev.vars.example."
