#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# Provisions what the Concierge needs outside the repo (#34): an authenticated
# AI Gateway with logging and a spend limit, an xAI key, and the Worker secrets
# in .dev.vars (for `wrangler dev`) and on the deployed Worker.
# Run from anywhere: ./scripts/setup-concierge.sh

cd "$(dirname "$0")/.."
ENV_FILE=".dev.vars"

TOTAL_STAGES=7
TOTAL_MINUTES=15

GATEWAY_DEFAULT="jorgemasta-com"
MODEL="grok-4.3"

banner "Concierge: AI Gateway + xAI setup"

# ── 1. Account ID ─────────────────────────────────────────────────────────
stage "Cloudflare account ID" 1
say "The gateway URL is scoped to your Cloudflare account."
say "It's the same value as the CLOUDFLARE_ACCOUNT_ID repo secret used by CI."
if npx --no-install wrangler whoami >/dev/null 2>&1; then
  note "wrangler is logged in. Your accounts:"
  npx --no-install wrangler whoami 2>/dev/null | grep -iE "account|│" || true
else
  open_url "https://dash.cloudflare.com/"
  step "Open the account → Account home → the ⋯ menu next to the account name → Copy account ID."
fi
ask CF_ACCOUNT_ID "Paste the account ID:"
write_env CF_ACCOUNT_ID "$CF_ACCOUNT_ID"
pause

# ── 2. Create the gateway ─────────────────────────────────────────────────
stage "Create the AI Gateway" 2
open_url "https://dash.cloudflare.com/${CF_ACCOUNT_ID}/ai/ai-gateway"
step "Click 'Create Gateway' and name it ${BOLD}${GATEWAY_DEFAULT}${RESET} (or your own name)."
step "Open the gateway → Settings → make sure log collection is ON."
note "Logs keep visitors' questions and answers, which feed future evals (spec #30, story 53)."
ask CF_AI_GATEWAY "Gateway name (ID) you created [${GATEWAY_DEFAULT}]:"
CF_AI_GATEWAY="${CF_AI_GATEWAY:-$GATEWAY_DEFAULT}"
write_env CF_AI_GATEWAY "$CF_AI_GATEWAY"
pause

# ── 3. Authenticated gateway ──────────────────────────────────────────────
stage "Lock the gateway with a token" 2
say "Without this, anyone who knows the account ID and gateway name can route"
say "requests through it and pollute your logs."
step "Gateway → Settings → 'Create authentication token' (it gets the AI Gateway Run permission)."
step "Copy the token now. It is shown only once."
step "Turn ON 'Authenticated Gateway' on the same settings page."
warn "The token is account-scoped: it can run any gateway in this account."
ask_secret CF_AIG_TOKEN "Paste the gateway token (hidden):"
write_env CF_AIG_TOKEN "$CF_AIG_TOKEN"
pause

# ── 4. Spend limit ────────────────────────────────────────────────────────
stage "Add a spend limit" 2
say "A budget, so a traffic spike or abuse can't produce a surprise bill."
step "Gateway → Settings → Spend limits → add a rule."
step "Scope: the whole gateway (no provider/model/metadata dimension)."
step "Pick an amount and window you're comfortable with (e.g. \$10, monthly)."
note "Spend limits only count models with known pricing. Stage 6 checks that grok requests show a cost."
pause "Press Enter once the rule is saved"

# ── 5. xAI key ────────────────────────────────────────────────────────────
stage "Create the xAI API key" 2
open_url "https://console.x.ai/"
step "Pick the team → API Keys → Create API key (name it e.g. jorgemasta-com-concierge)."
step "If it offers model restrictions, allow ${MODEL}."
step "Make sure the team has credits, or requests will fail with 4xx."
ask_secret XAI_API_KEY "Paste the xAI key (hidden, starts xai-):"
write_env XAI_API_KEY "$XAI_API_KEY"
pause

# ── 6. Smoke test ─────────────────────────────────────────────────────────
stage "Test ${MODEL} through the gateway" 3
url="https://gateway.ai.cloudflare.com/v1/${CF_ACCOUNT_ID}/${CF_AI_GATEWAY}/grok/v1/chat/completions"
say "POST $url"
body=$(mktemp)
code=$(curl -sS -o "$body" -w '%{http_code}' "$url" \
  -H 'content-type: application/json' \
  -H "Authorization: Bearer ${XAI_API_KEY}" \
  -H "cf-aig-authorization: Bearer ${CF_AIG_TOKEN}" \
  --data "{\"model\":\"${MODEL}\",\"messages\":[{\"role\":\"user\",\"content\":\"Reply with exactly: gateway ok\"}]}" \
  || echo "000")
if [[ "$code" == "200" ]]; then
  printf '  %s✓ HTTP 200%s  reply: %s\n' "$GREEN" "$RESET" \
    "$(grep -o '"content":"[^"]*"' "$body" | head -n1 | cut -d'"' -f4)"
else
  warn "HTTP $code. Response:"
  note "$(head -c 600 "$body")"
  note "401 from Cloudflare → token/Authenticated Gateway. 4xx from xAI → key, credits or model name."
  SKIPPED+=("Smoke test failed (HTTP $code): fix, then re-run this wizard (Enter keeps saved values)")
fi
rm -f "$body"
open_url "https://dash.cloudflare.com/${CF_ACCOUNT_ID}/ai/ai-gateway"
step "Open ${CF_AI_GATEWAY} → Logs: the request should be there, with tokens and a cost."
if ! confirm "Does the log entry show a cost (so the spend limit can enforce)?"; then
  SKIPPED+=("No cost on ${MODEL} logs: the spend limit won't count it. Check AI Gateway pricing support / custom costs")
fi

# ── 7. Deployed Worker secrets ────────────────────────────────────────────
stage "Push secrets to the deployed Worker" 3
say "Sets CF_ACCOUNT_ID, CF_AI_GATEWAY, CF_AIG_TOKEN and XAI_API_KEY as secrets"
say "on the production Worker (jorgemasta-com). The site itself doesn't change."
if confirm "Push the 4 secrets to the deployed Worker now?"; then
  if ! npx --no-install wrangler whoami >/dev/null 2>&1; then
    warn "wrangler isn't logged in. Run: npx wrangler login, then re-run this wizard."
    SKIPPED+=("Deployed Worker secrets (wrangler not logged in)")
  else
    for name in CF_ACCOUNT_ID CF_AI_GATEWAY CF_AIG_TOKEN XAI_API_KEY; do
      if printf '%s' "${!name}" | npx --no-install wrangler secret put "$name" >/dev/null 2>&1; then
        printf '  %s✓ set%s Worker secret %s\n' "$GREEN" "$RESET" "$name"
      else
        warn "couldn't set Worker secret $name"
        SKIPPED+=("Worker secret $name (npx wrangler secret put $name)")
      fi
    done
  fi
else
  SKIPPED+=("Deployed Worker secrets: run  npx wrangler secret bulk .dev.vars  when the Concierge ships")
fi
pause

finish
say "Next: ${BOLD}npx wrangler dev${RESET} reads ${ENV_FILE}. Names are documented in .dev.vars.example."
